### ISSUE TITLE
Move lockscreen down from top-most layer

### ISSUE THREAD

**Issue by emerali** [AlstonLin/TheLearningLock#38]
Currently it blocks lockscreen popups like custom music player lockscreen interfaces (ex. rocket player) along with the power menu

**Comment by AlstonLin** [comment]
This is due to the background view's drawing priority, which will be on top of all those things.

Other 3rd party lock screens (at least Microsoft's does not seem to support not blocking those either).
Please correct me if I'm wrong. Otherwise, close this issue since there isn't much we would be able to do about it.

**Comment by emerali** [comment]
AcDisplay seems to be able to do this:
https://play.google.com/store/apps/details?id=com.achep.acdisplay&hl=en

and so does Echo 
https://play.google.com/store/apps/details?id=com.doublelabs.androscreen.echo&rdid=com.doublelabs.androscreen.echo

**Comment by emerali** [comment]
It seems like (through playing around with Echo) that if the status bar is visible, the power menu can be displayed

music player interfaces are a different issue though, Rocket Player seems to be able to put an overlay on AcDisplay but not Echo

**Comment by AlstonLin** [comment]
Sounds like how the app was before #31 merged.
The problem with having the actual status bar visible is that if there's a different status bar color, then the UI would look extremely weird. Since we can't actually change the status bar color from a Service, adding our own custom status bar was the best we can do (along with some other major 3rd party lock screens).

Right now, we want to prioritize having a consistent UI for the lock screen over this issue. Is there a workaround to this you can think of? If not, then we'll close this issue
